name: "CI/CD NPM"

on:
  pull_request:
    branches: [feature/service-workers]
  push:
    branches: [feature/service-worker]
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    # needs: [publish]
    runs-on: ubuntu-latest
    env:
      main_source_path: "./"
      release_path: "dist/"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: "Release"
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
